[#5] [Standalone] Add Gimel Standalone Feature to Gimel
Make sure you have checked all steps below.


### Checklist:
<!--- Go over all the following points. Check boxes that apply to this pull request -->
- [x] This pull request updates the documentation
- [ ] This pull request changes library dependencies
- [x] Title of the PR is of format (example) : [#25][Github] Add Pull Request Template
- [x] This PR includes the URL to the GitHub Issue 

### What is the purpose of this pull request?
The purpose of this PR is to add Gimel Standalone feature. It addresses ISSUE-5 (https://github.com/paypal/gimel/issues/5) 

### How was this change validated?
It was tested on local

### Commit Guidelines
- [x] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

diff --git a/build/gimel_functions b/build/gimel_functions
--- a/build/gimel_functions
+++ b/build/gimel_functions
@@ -35,6 +35,26 @@ check_error()
 	fi
 }
 
+#----------------------------function will check for error code & warn if failure----------------------------#
+
+#usage : check_warning <$?> <custom_error_code>
+#Example: Check_warning < pass $? from the shell command > < Custom Message for errorcode -gt 0 >
+
+
+check_warning()
+{
+
+        cmd_error_code=$1
+        pgm_exit_code=$2
+        pgm_exit_msg=$3
+        if  [ ${cmd_error_code} -gt 0 ]; then
+                write_log "WARNING ! ${cmd_error_code} ${pgm_exit_code} ${pgm_exit_msg}"
+        else
+                echo ""
+        fi
+}
+
+
 
 #----------------------------function will write the message to Console / Log File----------------------------#
 
@@ -47,3 +67,24 @@ write_log()
         echo ${to_be_logged}
 }
 
+#-----------------------------------Executes a Command--------------------------------------------------------#
+
+
+
+#Usage : run_cmd < The command to execute > 
+
+run_cmd()
+{
+       cmd=$1
+       if [ -z $2 ]; then 
+         fail_on_error="break_code"
+       else
+         fail_on_error=$2
+       fi 
+       write_log "Executing Command --> $1"
+       $cmd
+       error_code=$?
+       if [ ! $fail_on_error = "ignore_errors" ]; then
+           check_error $error_code "$cmd"
+       fi
+}
